version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    volumes:
      - /home/data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    network_mode: "host"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.2
    environment:
     - "ELASTICSEARCH_URL=http://localhost:9200"
    ports:
      - "5601:5601"
    network_mode: "host"
